### ISSUE TITLE
Can't build project - Resulting minified file is "broken"

### ISSUE THREAD

**Issue by rinogo** [rajeshwarpatlolla/ionic-timepicker#102]
`gulp build` doesn't work quite right.  It executes without errors, but the resulting minified file does not function correctly.  (I get an error in my web browser about the template not being loaded)

The problem is that for some reason, the ionic-timepicker.templates dependency is not being injected.  This explains why the template can't be loaded.  To get around this problem, I simply build the project and then manually insert the ionic-timepicker.templates dependency in the minified file.  This works, but is a bit of a nuisance, especially for other devs who might not be savvy enough to determine what is wrong.

How can this be fixed?

**Comment by fonini** [comment]
The error is `ionic-timepicker/src/ionic-timepicker.module.js`. You have to uncomment the `'ionic-timepicker.templates'` line and build again.

@rajeshwarpatlolla Any chance to get this fixed? Thanks!

**Comment by rajeshwarpatlolla** [comment]
Yes you are right. You need to uncomment in order to build it.

**Comment by rinogo** [comment]
Ha!  I can't believe I missed that.  Thanks, @fonini, and @rajeshwarpatlolla.

Should I submit a PR, @rajeshwarpatlolla?
