### ISSUE TITLE
File references in index.html

### ISSUE THREAD

**Issue by thomashrabe** [rajeshwarpatlolla/ionic-timepicker#104]
Hi Rajesh,

great work! I use your picker for a long time now. 
Just ran an update and realize that my previous dependencies from an older version do not hold anymore. 
CSS files do not exist anymore. Can you please comment? Had to comment the dependency, but the pickers do not show anymore.

```
<!-- <link href="lib/ionic-datepicker/dist/style.css" rel="stylesheet">  -->
  <!-- path to ionic/angularjs js -->
  <!-- <script src="lib/ionic-datepicker/dist/templates.js"></script> -->
  <script src="lib/ionic-datepicker/dist/ionic-datepicker.bundle.min.js"></script> 

  <!-- <link href="lib/ionic-timepicker/dist/style.css" rel="stylesheet"> -->
  <!-- path to ionic/angularjs js -->
  <!-- <script src="lib/ionic-timepicker/dist/templates.js"></script> -->
  <script src="lib/ionic-timepicker/dist/ionic-timepicker.bundle.min.js"></script>
```

**Comment by rajeshwarpatlolla** [comment]
Now in the latest version all those files are bundles into one single file. So you don't need to worry about the remaining files.
