### ISSUE TITLE
Minute arrows not visible. 

### ISSUE THREAD

**Issue by vt-ombalakumar** [rajeshwarpatlolla/ionic-timepicker#109]
Hi I am working in ionic , installed ionic-timepicker, did as shown in demo, used in my application. but when open time picker the up arrow and down arrow is not shown. 
var ipObjt1 = {

    callback: function(val) { //Mandatory
      if (typeof(val) === 'undefined') {
        console.log('Time not selected');
      } else {
        var selectedTime = new Date(val * 1000);

        hours = selectedTime.getUTCHours();
        window.localStorage.setItem("getHours", hours);
        if (hours > 12) {
          hours -= 12;
        } else if (hours === 0) {
          hours = 12;
        }
        var selectedTimes = (hours < 10 ? "0" : "") + hours + ":00";
        $scope.pColTime = selectedTimes;

      }
    },
    format: 12, //Optional
    step: 15, //Optional
    setLabel: 'Set',
    setButtonType: 'button-positive', //Optional
    closeButtonType: 'button-stable' //Optional    //Optional
  };
  $scope.openSampleTime = function() {
    ionicTimePicker.openTimePicker(ipObjt1);
  }
compile and run on genymotion emulator anroid api 4.4.4 
[Screen shot of time picker](https://drive.google.com/file/d/0B8kfoBE4Bx--QWd4Q3N5d25BbWs/view?usp=sharing)

**Comment by rajeshwarpatlolla** [comment]
It's working fine in the demo page http://rajeshwarpatlolla.github.io/TimePickerForIonicFramework/demo/#/tab/timepicker. Please do cross check the documentation.
