### ISSUE TITLE
Steps can get corrupted

### ISSUE THREAD

**Issue by aaronksaunders** [rajeshwarpatlolla/ionic-timepicker#22]
If I use the current time as the starting time and that time is not a factor of the defined `step` parameter, the time selector display gets corrupted, meaning you can get negative numbers and numbers that are not valid minutes

**Comment by rajeshwarpatlolla** [comment]
Let me see your code first, then i will be able to get some idea of what you are doing, and some thing is going wrong.

**Comment by aaronksaunders** [comment]
don need any code, just set the start time of you time-picker to 12:59 am with a 15 minute interval and it will get wacky real quick

**Comment by rajeshwarpatlolla** [comment]
I have implemented for only 1 minute and 15 minute increments. If i set the start time to 12:59 PM, it wont solve the issue. If you wish to use this component, i suggest to use a step value which is a factoe of 1 or 15 only.
