### ISSUE TITLE
set time to current time

### ISSUE THREAD

**Issue by anshulklr** [rajeshwarpatlolla/ionic-timepicker#31]
how can i set the timepicker to show the current time?

**Comment by rajeshwarpatlolla** [comment]
Don't set any value to `epochTime` in the below line 

`$scope.slots = {epochTime: 12600, format: 12, step: 15};`
Please read the instructions https://github.com/rajeshwarpatlolla/ionic-timepicker.

**Comment by anshulklr** [comment]
$scope.slots = { format: 12, step: 15};
is this what you are talking about?

**Comment by rajeshwarpatlolla** [comment]
Oh, sorry. I just checked it, i didn't implemented such functionality. Thanks for raising this bug. This will be a feature. 

But for now you can follow the below procedure.

```
var date = new Date();
var minutes = date.getMinutes();
var hours = date.getHours();
var epoch = hours*60*60 + minutes*60;
```

Then 
date = Thu May 28 2015 13:42:29 GMT+0530 (IST)
minutes = 42
hours = 13
epoch = 49320

You can pass this `epoch` to it.
