### ISSUE TITLE
Prevent opening keyboard on iPhone

### ISSUE THREAD

**Issue by jvaclavik** [rajeshwarpatlolla/ionic-timepicker#33]
Hello, 
I tried ionic timepicker on iPhone, and there is problem with opening keyboard. It could be nice if keyboard doesn't show in that case.

See the problem here:
https://www.dropbox.com/s/lpzw3c7cjqdsp78/timepicker.mov?dl=0

Best regards,

Jan

**Comment by rajeshwarpatlolla** [comment]
Even i tried and tested number of times, but i didn't find this issue. Even few others are also using this component. They had some functionality related issues, which are already fixed. Could you please try this with the latest version of this component?

**Comment by rajeshwarpatlolla** [comment]
I am unable to reproduce this issue. I am not getting any keyboard on opening of time picker.

**Comment by ofershap** [comment]
It's happening when adding an < input > element inside the ionic-timepicker elemnt (in order to display a placeholder, and afterward the selected value)
