### ISSUE TITLE
.col missing templates

### ISSUE THREAD

**Issue by yatiq** [rajeshwarpatlolla/ionic-timepicker#34]
Hello.
Devices with android 4.2.2 and low resolution may display incorrect with included template.
To prevent popup display incorrect add .col to span class:
<span class="button-small col col-offset-20 col-25">

Thx! Great job anyway!!

Sorry my english :)

**Comment by rajeshwarpatlolla** [comment]
I didn't understood clearly. Could you please go in to detail? If there is some screen shot that would be better.

**Comment by yatiq** [comment]
Sorry my bad english!!
I try to explain me.
In timePickerTemplates.js to show popup you uses (in 24hr i.e.):
< span class="button-small col-offset-20 col-25">...</ span>
< label class="col-10 timePickerColon">:</ label>
< span class="button-small col-25">...</ span>
witch is incorrect and display incorrect with android 4.2.2 and low res devices.
Correct is (note 'col')

< span class="button-small col col-offset-20 col-25">...</ span>
< label class="col col-10 timePickerColon">:</ label>
< span class="button-small col col-25">...</ span>

And some css improvements to semicolon.
Trying one screenshot :)

**Comment by rajeshwarpatlolla** [comment]
Do you have a screen shot now?

**Comment by comapedrosa** [comment]
@yatiq awesome fix! Thank you! I didn't know what to do! @rajeshwarpatlolla if you want a screenshot just run your code in an Android 4.2.2 or below and you'll see the arrows and the inputs displaying in a same line...

**Comment by rajeshwarpatlolla** [comment]
Sorry, but i don't have that version of android device. If you can provide me a screen shot that would be really great.

**Comment by rajeshwarpatlolla** [comment]
I pushed the changes to develop branch. You will see the changes in the next release.
