### ISSUE TITLE
Call programmatically / Ionic-datepicker unification

### ISSUE THREAD

**Issue by raphaklaus** [rajeshwarpatlolla/ionic-timepicker#37]
Hello, in some cases datepicker and timepicker are used together, is there a method to connect these two directives? Or call timepicker programmatically inside a datepicker callback?

**Comment by rajeshwarpatlolla** [comment]
For now there is no such functionality implemented.

**Comment by loicknuchel** [comment]
You can do `element.find('ionic-timepicker').triggerHandler('click');` on the ionic-datepicker callback.
But this is not really convenient...

**Comment by rajeshwarpatlolla** [comment]
Please check with the latest version v0.5.0
