### ISSUE TITLE
Callback method is not fired with time picker.

### ISSUE THREAD

**Issue by bdairy** [rajeshwarpatlolla/ionic-timepicker#38]
I have my time picker  in  an ionic modal with date picker as well,, the time picker sets the model value correctly,, but not calling the call back method,. on the other hand datepicker is working just fine..

here is my code:

```
  <ionic-timepicker etime="filterStartTimeDisplay.epochTime"        format="filterStartTimeDisplay.format" step="filterStartTimeDisplay.step"   callback="timePickerCallback">   
         <p > <standard-time-meridian  etime='filterStartTimeDisplay.epochTime'></standard-time-  meridian></p>
          </ionic-timepicker>


 $scope.timePickerCallback = function (val) {
           if (typeof (val) === 'undefined') {
            console.log('Time not selected');
           } else {
             console.log('Selected time is : ', val);    // `val` will contain the selected time in epoch
           }
        };
```

as you can see the object filterStartTimeDisplay is set correctly,, but the time picker callback function is not working... the log is not generated.

**Comment by rajeshwarpatlolla** [comment]
Are you using the callback in the same controller in which you are using the timepicker?

**Comment by bdairy** [comment]
Yes of course .

**Comment by rajeshwarpatlolla** [comment]
If so, the callback should be called for sure. Are you still facing this issue or resolved?

**Comment by rajeshwarpatlolla** [comment]
If you have write the callback function, in the respected controller, then for sure, it should work.
