### ISSUE TITLE
Class starting with a digit are invalid

### ISSUE THREAD

**Issue by JeanMeche** [rajeshwarpatlolla/ionic-timepicker#41]
Your classes `12HourTimePickerChildDiv` and `24HourTimePickerChildDiv` are invalid.

To be valid the first character must be an underscore (_), a hyphen (-), or a letter(a–z). 

This prevent the popup to be customized a little.

**Comment by rajeshwarpatlolla** [comment]
Yes, you are right. I even forgot about these class names. Thanks for raising this bug. I will implement this in the next release and then i will close this issue.

**Comment by rajeshwarpatlolla** [comment]
Checkout the v0.2.1 for this bug fix.
