### ISSUE TITLE
setting title of timepicker

### ISSUE THREAD

**Issue by hafl1016** [rajeshwarpatlolla/ionic-timepicker#43]
Hello,
Thanks for this timepicker, it works great.
Can you tell me how to set the title of the timepicker, I tried:
 `
<ionic-timepicker etime="slotsStart.epochTime" format="slotsStart.format" step="slotsStart.step" callback="setStartTime" title="test">`
but this isn't working.

**Comment by rajeshwarpatlolla** [comment]
Is test variable defined in your controller?

**Comment by hafl1016** [comment]
ahh Thank you
Thought I have to write the title directly in there (so here the title would be "test"
But apparently the value of $scope.test is the title
Thanks for the fast and helpful answer!
