### ISSUE TITLE
Button text doesn't update automatically

### ISSUE THREAD

**Issue by taytus** [rajeshwarpatlolla/ionic-timepicker#46]
I'm having the same issue with ionic-datepicker too.
Everything works, the callback is triggering and logging the right information. The buttons start with the default text, but it doesn't update after the selection.

Template:
    <ionic-timepicker input-obj="timePickerObject">
      <button class="button button-block button-positive overflowShow">
        <standard-time-meridian etime='timePickerObject.inputEpochTime'></standard-time-meridian>
      </button>
    </ionic-timepicker>
Controller:

 $scope.timePickerObject = {
        inputEpochTime: ((new Date()).getHours() \* 60 \* 60),  //Optional
        step: 15,  //Optional
        format: 12,  //Optional
        titleLabel: '12-hour Format',  //Optional
        setLabel: 'Set',  //Optional
        closeLabel: 'Close',  //Optional
        setButtonType: 'button-positive',  //Optional
        closeButtonType: 'button-stable',  //Optional
        callback: function (val) {    //Mandatory
          timePickerCallback(val);
        }
      };
      function timePickerCallback(val) {
        if (typeof (val) === 'undefined') {
          console.log('Time not selected');
        } else {
          var selectedTime = new Date(val \* 1000);

```
      console.log('Selected epoch is : ', val, 'and the time is ', selectedTime.getUTCHours(), ':', selectedTime.getUTCMinutes(), 'in UTC');
    }
  }
```

**Comment by rajeshwarpatlolla** [comment]
Once you get the selected value into the controller you can assign that value to whatever the variable you wish to assign. Try setting the returned value to the variable `$scope.timePickerObject. inputEpochTime`

**Comment by taytus** [comment]
Thank you so much! It worked :)

**Comment by rajeshwarpatlolla** [comment]
You are welcome.
