### ISSUE TITLE
Decrementing minutes skips over "00"

### ISSUE THREAD

**Issue by schowdhuri** [rajeshwarpatlolla/ionic-timepicker#48]
This can be seen on the demo page too: http://rajeshwarpatlolla.github.io/TimePickerForIonicFramework/demo/#/tab/timepicker
On decrementing the minutes using the arrow button, the value goes straight from, say 10 to 50 instead of 10 -> 00 -> 50.
The increment functionality works as expected: 50 -> 00 -> 10

**Comment by mattchue** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
This has been fixed in the latest commit to the master branch. Please check it in the [latest commit](https://github.com/rajeshwarpatlolla/ionic-timepicker/commit/38bb70964080ceab159b4f0fc0d7145ec90547a1)
