### ISSUE TITLE
Popover issue

### ISSUE THREAD

**Issue by rajild** [rajeshwarpatlolla/ionic-timepicker#50]
Your example is fine,  you are using timepicker in page.  I am having issue when i use time-picker in ionic popover page.  See below image.

![image](https://cloud.githubusercontent.com/assets/6926340/9830480/35e6a722-594d-11e5-8afb-16dd38624cb0.png)

If user clicks time multiple times then multiple timepicker is displayed and application crashes.  Is it possible to close timepicker when user click outside?

**Comment by rajeshwarpatlolla** [comment]
So you can add a validation there, so that once the user clicks on the time, then disable the button or the area, so that the user won't be able to click it again.
