### ISSUE TITLE
Enable numeric keyboard

### ISSUE THREAD

**Issue by aheadzen** [rajeshwarpatlolla/ionic-timepicker#52]
I need user to enter specific time as 3:35, but they have press down 35 times to show up exact minute. What do you suggest?

**Comment by rajeshwarpatlolla** [comment]
This component has the 5 minute and 15 minute increment and decrement features. So maybe you can use that feature. But there is no input which will prompt for a numeric keypad as of now.

**Comment by aheadzen** [comment]
I need users to enter "exact" time correct to minutes and I noted that input box has been "disabled" in code. May be you could make it optional and disable/enable based on options provided. This will be highly helpful.
