### ISSUE TITLE
Time Picker as an inline control

### ISSUE THREAD

**Issue by gigocabrera** [rajeshwarpatlolla/ionic-timepicker#55]
Can I display the ionic-timepicker as an inline control on my form so it is always visible when the user navigates to that view? If so, how?

**Comment by rajeshwarpatlolla** [comment]
Currently it i dynamic, means it can be opened only when the user clicks on the button(in other terms when the click event is fired).
If you wish to display as an form element, then you can show it in a div without a button.

**Comment by gigocabrera** [comment]
I tried a div without a button but that didn't work. Maybe it can be added as a feature for future release.
