### ISSUE TITLE
How to convert string time to epoch time

### ISSUE THREAD

**Issue by gigocabrera** [rajeshwarpatlolla/ionic-timepicker#57]
This is what I get back from the database:
    1) 02:30 PM
    2) 12:00 AM
    3) 08:50 PM

How can I convert string time to epoch time in order to use your ionic-timepicker control?

**Comment by rajeshwarpatlolla** [comment]
`var x = new Date();` gives you the current epoch. Get the hours and minutes from your string(02:30 PM). Then set those minutes and hours to the current epoch like `x.setMinutes(<your minutes>)` and `x.setHours(<your hours>)`. If it is PM, then add 12 hours to it. Then you will get the epoch time in your variable `x`.

**Comment by gigocabrera** [comment]
As always, thank you for your help. That worked!!!
