### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by aishahismail** [rajeshwarpatlolla/ionic-timepicker#59]
function timePickerCallback(val) {
        if (typeof (val) === 'undefined') {
    console.log('Time not selected');
  } else {
    var selectedTime = new Date(val \* 1000);
    console.log('Selected epoch is : ', val, 'and the time is ', selectedTime.getUTCHours(), ':', selectedTime.getUTCMinutes(), 'in UTC');
  }
}

at the code above, return value "val" is in what format? second?

**Comment by rajeshwarpatlolla** [comment]
It will return the epoch time. Please check the demo at http://rajeshwarpatlolla.github.io/TimePickerForIonicFramework/demo/#/tab/timepicker
Look at the console once you selected the time.
