### ISSUE TITLE
Cannot set initial time

### ISSUE THREAD

**Issue by sventer** [rajeshwarpatlolla/ionic-timepicker#61]
Hi

I'm unable to set the initial time **inputEpochTime**. Even the example does not work.

I read the value set from localstorage and set inputEpochTime with that value i.e. 24420

**Comment by rajeshwarpatlolla** [comment]
That's not the proper value. Please convert the epoch you are passing to the component. multiply with 1000 and then try it. And also please take a look at the [demo](http://rajeshwarpatlolla.github.io/TimePickerForIonicFramework/demo/#/tab/timepicker).

**Comment by sventer** [comment]
Still not working. And like I said the example does not work either.

![untitled](https://cloud.githubusercontent.com/assets/6451914/11865663/2d0d923a-a4ae-11e5-8e17-4dbbed6790ff.png)
![untitled1](https://cloud.githubusercontent.com/assets/6451914/11865664/2d163ff2-a4ae-11e5-9a36-3384960f78ea.png)

Also `new Date().getHours() * 60 * 60` will give a vale similar to that I quoted above.

**Comment by rajeshwarpatlolla** [comment]
The example is working fine. It will pick the current hour. Are you getting any errors on the console?

**Comment by sventer** [comment]
no I don't.

I have looked at all your documentation and the demo before contacting you.

Is there a problem with that code snippet I added?

**Comment by sventer** [comment]
I solved the problem, the variable, used to set inputEpochTime, was not initialized with the correct value.

Thanks

**Comment by uzumakinaruto123** [comment]
@rajeshwarpatlolla 

i have the same issue.......... 

here is my object, which is same as demo

> $scope.timePickerObject = {
>   inputEpochTime: ((new Date()).getHours() \* 60 \* 60),  //Optional
>   step: 15,  //Optional
>   format: 12,  //Optional
>   titleLabel: '12-hour Format',  //Optional
>   setLabel: 'Set',  //Optional
>   closeLabel: 'Close',  //Optional
>   setButtonType: 'button-positive',  //Optional
>   closeButtonType: 'button-stable',  //Optional
>   callback: function (val) {    //Mandatory
>     timePickerCallback(val);
>   }
> };

if i use button with :- 

`<standard-time-meridian etime='timePickerObject.inputEpochTime'></standard-time-meridian>`

the button text is blank instead of current time !

then i tried displaying it with...

<standard-time-meridian etime='timePickerObject.inputEpochTime'>  {{timePickerObject.inputEpochTime}}</standard-time-meridian>

It displays the time but as **EPOCH FORMAT**

**Comment by rajeshwarpatlolla** [comment]
You need to have [this directive](https://github.com/rajeshwarpatlolla/my-angularjs-directives#standard-time-meridian) in order to show it in the correct format.

**Comment by uzumakinaruto123** [comment]
Thanks alot :)  sorry for that ! works great..
