### ISSUE TITLE
Manual Input for hours and minutes

### ISSUE THREAD

**Issue by pogramos** [rajeshwarpatlolla/ionic-timepicker#62]
Can't change the values manually.
e.g.: i'm in 0 and need to put value 30, so i need to click up for 30 times, and so on.

**Comment by rajeshwarpatlolla** [comment]
You can add one more property `step` to increment by certain value. Please take  a look at the description. And manual changing is not allowed as of now.

**Comment by MarkDsantos** [comment]
Is there an option for this?
