### ISSUE TITLE
Popup Issue

### ISSUE THREAD

**Issue by GrimGX** [rajeshwarpatlolla/ionic-timepicker#63]
Hi rajeshwarpatlolla,

Perhaps you can help me. I am having an issue wherein the popup for your timepicker does not show correctly on a mobile device. It grays out the content behind it but the popup is not visible. Please see the below code and attached pictures. (the code is basically not changed from your original implementation)

//CONTROLLER
$scope.timePickerObject = {
        inputEpochTime: ((new Date()).getHours() \* 60 \* 60),  //Optional
        step: 15,  //Optional
        format: 12,  //Optional
        titleLabel: '12-hour Format',  //Optional
        setLabel: 'Set',  //Optional
        closeLabel: 'Close',  //Optional
        setButtonType: 'button-positive',  //Optional
        closeButtonType: 'button-stable',  //Optional
        callback: function (val) {    //Mandatory
            timePickerCallback(val);
        }
    };

//HTML (I tried to add it here but it doesnt show. sorry new to github.)
    <ionic-timepicker input-obj="timePickerObject">
        <button class="button button-block button-positive overflowShow" style="width:90%; margin-left:5%;">
            <standard-time-meridian etime='timePickerObject.inputEpochTime'></standard-time-meridian
        </button>
    </ionic-timepicker>

I have also ensured that the module is required in my app module.
![before click](https://cloud.githubusercontent.com/assets/16589686/12165593/e092bb80-b527-11e5-88ba-2d7de9c9c0d8.png)
![after click](https://cloud.githubusercontent.com/assets/16589686/12165597/e6f937b0-b527-11e5-9c66-7f13194e1484.png)

**Comment by CarsonChen1129** [comment]
Did you catch any error from the console? (If you are using Chrome, click "View - Developer - Developer Tools - Console")
And as Rajesh mentioned in his documentations:

> input-obj (Mandatory) : This is an object. We have to pass an object as shown above.
> standard-time-meridian is the directive i am using here to show the time in string format instead of the 
>  epoch value. You can also use any of my directives to convert the epoch time to string format.

You need to include additional directives on your selection. The link is here: https://github.com/rajeshwarpatlolla/my-angularjs-directives

Hope my info helps.
