### ISSUE TITLE
Selecting 12:00 AM Bug

### ISSUE THREAD

**Issue by Chuckv01** [rajeshwarpatlolla/ionic-timepicker#70]
I believe there is a bug with the 12-hour display when 12:00 AM is selected. Steps to reproduce:
- Open a time picker and configure it to 12:00 AM
- Select time
- Re-open the time picker

The time picker will re-appear as 00:00 AM. Note it is displaying "00" instead of "12".

**Comment by aldour** [comment]
I am having a similar issue.
- Initially, the time picker is set to 09:00 PM
- Select 00:00
- `<standard-time-meridian etime='timePickerObject.inputEpochTime'></standard-time-meridian>` still shows 09:00 PM, as `timePickerObject.inputEpochTime` cannot be set to 0

**Comment by rajeshwarpatlolla** [comment]
Please check with the latest version v0.5.0
