### ISSUE TITLE
unable to use setLabel and closeLabel together with ng-translate

### ISSUE THREAD

**Issue by grapemix** [rajeshwarpatlolla/ionic-timepicker#71]
Hi,

Thanks for the hardworking for this plugin, it is awesome.

I do have problem to use the setLabel and closeLabel settings together with ng-translate. ng-translate will return a promise which means that I cannot get the result immediately(when the directive being init/render). I tried the following two methods, but failed.

1) Put the entire $scope.timePickerObject = {...} inside the ng-translate promise
Result: ionic-timepicker return error because timePickerObject is missing during init

2) Put the entire $scope.timePickerObject = {...} outside the ng-translate promise, but keeping $scope.timePickerObject.setLabel and closeLabel inside the ng-translate promise
Result: ionic-timepicker runs fine but setLabel and closeLabel settings are not used since the link fxn only runs once at the beginning and there's where setLabel and closeLabel being aside.

Any good idea to resolve this problem? Adding a watch for setLabel and closeLabel will be pretty inefficient though.

Thanks.

**Comment by rajeshwarpatlolla** [comment]
Please use v 0.5.0 to resolve this issue. With this version of component you can configure the component.
