### ISSUE TITLE
setMinSecs: $scope.time.hours string transformation

### ISSUE THREAD

**Issue by philonor** [rajeshwarpatlolla/ionic-timepicker#72]
**Context**
In [ionic-timepicker.provider.js, Line 99](https://github.com/rajeshwarpatlolla/ionic-timepicker/blob/master/src/ionic-timepicker.provider.js#L99), [Number.prototype.toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) is used to transform `$scope.time.hours` into a string.

**Problem**
As "The number is rounded if necessary (...)", this results in the subsequent hour to be displayed in the picker as soon as the specified `ipTime` has a minute component of >= 30.

![image](https://cloud.githubusercontent.com/assets/5816039/14499904/439660dc-01a0-11e6-8cf3-fb31e783c337.png)
![image](https://cloud.githubusercontent.com/assets/5816039/14499884/37f561c4-01a0-11e6-8119-a760eaaf5ede.png)

![image](https://cloud.githubusercontent.com/assets/5816039/14499930/5e2925f6-01a0-11e6-8ce9-4ecb10d3a063.png)
![image](https://cloud.githubusercontent.com/assets/5816039/14499922/56310b48-01a0-11e6-9b2d-e3f5311f87cf.png)

**Possible solution**
Use [`Math.floor()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math/floor) instead.

**Workaround**
![image](https://cloud.githubusercontent.com/assets/5816039/14500177/67f1dcee-01a1-11e6-8f68-28d49296af15.png)

**Comment by matteo-sys** [comment]
+1 Math.floor() -> please commit to master

**Comment by jdnichollsc** [comment]
+1 Please solve the issue! :dancers:

**Comment by philonor** [comment]
Can be closed, see PR https://github.com/rajeshwarpatlolla/ionic-timepicker/pull/79.

**Comment by jdnichollsc** [comment]
Thanks! :+1:
