### ISSUE TITLE
Use unix timestamp for inputTime and return value

### ISSUE THREAD

**Issue by philonor** [rajeshwarpatlolla/ionic-timepicker#73]
**Problem**
- Return value (number of seconds) is "local time"
- Turning number of seconds into usable representation (unix timestamp / moment.js) requires unnecessary effort (if timezone offset or [DST](https://en.wikipedia.org/wiki/Daylight_saving_time) has to be taken into account)

**Possible solution**
Always use a unix timestamp representation, both for specifying inputTime and also for return value.

**Workaround**
![image](https://cloud.githubusercontent.com/assets/5816039/14500681/4b9b1950-01a3-11e6-8ddc-817c1f867603.png)

**Comment by blparker** [comment]
+1

**Comment by dts** [comment]
I actually disagree, or think this should be optional.  The headaches that this introduces from a timezone perspective alone is enough to complicate this library a great deal.

**Comment by rajeshwarpatlolla** [comment]
Users may or may not use the moment library. Even if they use moment library you can convert the returned epoch to the local timezone, and then you can easily convert it using moment methods.
