### ISSUE TITLE
Unable to to add 1 hour current inputTime

### ISSUE THREAD

**Issue by muhsin-k** [rajeshwarpatlolla/ionic-timepicker#74]
I want add 1 hour to current time for showing inputEpochTime as this time.How to do that?

**Comment by rajeshwarpatlolla** [comment]
While passing the `inputTime`, you can add one hour(60*60 seconds) and pass it to the `ionicTimePicker.openTimePicker(<object>)` method.

**Comment by muhsin-k** [comment]
If i add  ((new Date()).getHours()) + (60 \* 60) to inputEpochTime.It is showing 01:00 time.Similarly
 ((new Date()).getHours()) + (60 \* 60_2)--->02:00 
 ((new Date()).getHours()) + (60 \* 60_3)--->03:00 etc.
(Here the current time is 18:00 ).Can i get the display time as by adding one hour to current utc time?

**Comment by rajeshwarpatlolla** [comment]
You need to pass `inputTime: (((new Date()).getHours() * 60 * 60) + (60*60)`

**Comment by muhsin-k** [comment]
My controller code is,

```

$scope.timePickerObject = {
    // inputEpochTime: ((new Date()).getHours() + (30 * 60 * 1000)), //Optional
    inputEpochTime: (((new Date()).getHours() * 60 * 60) + (60 * 60)),
    step: 5, //Optional
    format: 24, //Optional
    titleLabel: 'Enter Departure Time in UTC', //Optional
    setLabel: 'OK', //Optional
    closeLabel: 'CANCEL', //Optional
    setButtonType: 'button-positive', //Optional
    closeButtonType: 'button-stable', //Optional
    callback: function(val) { //Mandatory
        timePickerCallback(val);
    }
};

```

If the current time is 03:40:00,the time picker is showing 10:00 .
