### ISSUE TITLE
Time Picker Popup issues

### ISSUE THREAD

**Issue by lakhsmi** [rajeshwarpatlolla/ionic-timepicker#75]
Hi First of all  thanks for great plugin. I had an issues like when I am selecting time as 12PM it is showing the popup as 12AM . If we select 12AM in popup then it is showing 12PM .It is working reverse only in the case of 12 AM and 12 PM for other hours it is working fine.

**Comment by rajeshwarpatlolla** [comment]
Thank you so much @lakhsmi for finding this bug. This has been fixed in the latest release v0.5.1.

**Comment by lakhsmi** [comment]
Thank you very much for solving the issue. It's working perfectly now. I just upgraded to latest version.
