### ISSUE TITLE
gulp build => mising ionic-timepicker.templates

### ISSUE THREAD

**Issue by trivector-se** [rajeshwarpatlolla/ionic-timepicker#76]
Hello,

After running `gulp build` on master (no local changes), I get a 404 on the ionic-timepicker.html template. The ionic-timepicker.bundle.min.js is not generated exactly the same as the one in your repository. One difference is shown below - the ionic-timepicker.templates module is no longer present.

From master:

```
angular.module("ionic-timepicker",["ionic-timepicker.provider","ionic-timepicker.templates"]),angular.module("ionic-timepicker.provider",[]).provider("ionicTimePicker",function(){
```

After running `gulp build` on master:

```
angular.module("ionic-timepicker",["ionic-timepicker.provider"]),angular.module("ionic-timepicker.provider",[]).provider("ionicTimePicker",function(){
```

It looks like ng-html2js npm module is responsible for this maniplation. I get 2.0.2 when doing `npm install`. Maybe you have a different version?

Or should I not use `gulp build`, but instead some other command? Obviously without making any changes there is no point. But I plan to make changes including #73 and then allow changing date +/- a few as well.

**Comment by trivector-se** [comment]
The solution is to open src/ionic-timepicker.module.js and to uncomment line 3 with 'ionic-timepicker.templates'. Then when running `gulp make-build`  the resulting js file import the templates module correctly and there is no 404 for the template.

**Comment by rajeshwarpatlolla** [comment]
Yes, you are right @trivector-se.
