### ISSUE TITLE
Display time from 00:00 to 07:00

### ISSUE THREAD

**Issue by muhsin-k** [rajeshwarpatlolla/ionic-timepicker#77]
How can i display time from 00:00 to 07:00[No need of showing 08:00 to 23.59]?

**Comment by rajeshwarpatlolla** [comment]
The feature supports is incrementing and decrementing by certain number of minutes. Directly going to 07:00 is not possible with this component. But you can fork and customise as per ur  need.

**Comment by muhsin-k** [comment]
Can i display time 00.00 to 07.00 (Means i can select time from 00.00 to 07.00 only).I dont want to take time from 08.00 to 23.59?Is it possible?

**Comment by rajeshwarpatlolla** [comment]
I have already mentioned that such feature is not possible with the existing component.
