### ISSUE TITLE
Can you provide bundle.js not minified to allow editions in code?

### ISSUE THREAD

**Issue by vinimendes3** [rajeshwarpatlolla/ionic-timepicker#78]
I'm using ionic-timepicker and it's working very well, but in an specific project I want to customize the library in something, for example:

1) Change the order of button "Set" and "Cancel", putting the "Set" in right position and "Cancel" in left position.

2) Do not reset hour number when it reaches 24.

3) Change label in Popup Header to show, for example:
If time is 15:30 -> Label: 15:30 minutes
If time is 15:00 -> Label: 15 minutes
If time is 01:00 -> Label: 1 minute
If time is 00:30 -> Label: 30 seconds
If time is 00:01 -> Label: 1 second

The purpose of this project is to select how many minutes and seconds to retrieve this value to me, then I'm using hour area to select minutes and minute area to select seconds, because this I would like to change somethings in the library. Is it possible to provide not minified version to compile?

Thanks in advance

**Comment by vinimendes3** [comment]
Just as advice, studying your library in minified code I've noticed that you are using .toFixed() and when I was putting 00:30 to be showed, in the popup it was showing me 01:30, and if I put 01:30, in the popup it was showing 02:30, and so on... 

To solve this I've changed:

```
$scope.time.hours.toFixed(0);
```

to: 

```
Math.floor($scope.time.hours);
```

**Comment by rajeshwarpatlolla** [comment]
I hope you are expecting it to be a timer selection. But this component only supports the selection of time.
