### ISSUE TITLE
Doesn't work after gulp build - needs comment removed

### ISSUE THREAD

**Issue by distrotek** [rajeshwarpatlolla/ionic-timepicker#83]
I think you forgot to remove a comment.

In ionic-timepicker.module.js

angular.module('ionic-timepicker', [
  'ionic-timepicker.provider',
  //'ionic-timepicker.templates'
]);

Great work btw.

**Comment by pabl0xf** [comment]
After build 
ionic-timepicker.html is missing when I run the App. The mimify bundle include in dist file is old and contains an already solve bug (solve in src ).

**Comment by distrotek** [comment]
It will build properly if you uncomment the line in ionic-timepicker.module.js

Change:

angular.module('ionic-timepicker', [
'ionic-timepicker.provider',
//'ionic-timepicker.templates'
]);

To:

angular.module('ionic-timepicker', [
'ionic-timepicker.provider',
'ionic-timepicker.templates'
]);

**Comment by rajeshwarpatlolla** [comment]
In `src` folder we don't need `ionic-timepicker.templates` as a dependent module. We only need it in `dist` folder.
