### ISSUE TITLE
Change step by default

### ISSUE THREAD

**Issue by Davids89** [rajeshwarpatlolla/ionic-timepicker#87]
Hello, I'm rendering a time picker when an ion-toogle makes true a variable. I have a case when the variable is true since the beginning and the object is declared with the default step (15) and I need to set it in 5.

Any solution?

**Comment by GIOkafor** [comment]
Also is it possible to change the step value to something other than 10,15,20,30?

**Comment by rajeshwarpatlolla** [comment]
Every time before opening the timepicker you need to rebuild the object that you are passing to this component, with updated `step` value.
