### ISSUE TITLE
esto tambien es una porqueria setMinSecs

### ISSUE THREAD

**Issue by ricardo-hl** [rajeshwarpatlolla/ionic-timepicker#92]
function setMinSecs(ipTime, format) {
        moment.tz.setDefault('UTC');
          $scope.time.hours = ipTime / (60 \* 60);
        //$scope.time.hours = (((new Date()).getHours() \* 60 \* 60) + ((new Date()).getMinutes() \* 60));
          console.log('$scope.time.hours: '+$scope.time.hours);
          var rem = ipTime % (60 \* 60);
          console.log(rem);
          if (format == 12) {
            if ($scope.time.hours > 12) {
              $scope.time.hours -= 12;
              $scope.time.meridian = 'PM';
            } else {
              $scope.time.meridian = 'AM';
            }
          }
          $scope.time.minutes = rem / 60;

```
      $scope.time.hours = Math.floor($scope.time.hours);
      $scope.time.minutes = Math.floor($scope.time.minutes);

      if ($scope.time.hours.toString().length == 1) {
        $scope.time.hours = '0' + $scope.time.hours;
      }
      if ($scope.time.minutes.toString().length == 1) {
        $scope.time.minutes = '0' + $scope.time.minutes;
      }
      $scope.time.format = $scope.mainObj.format;

      console.log('$scope.time.hours: '+$scope.time.hours);

  }
```

**Comment by rajeshwarpatlolla** [comment]
Sorry, i don't understand your language. Could you please explain it in English?
