### ISSUE TITLE
is TimePicker time can be edited with keyboard instead of just steps intevals?

### ISSUE THREAD

**Issue by MayankLogiciel** [rajeshwarpatlolla/ionic-timepicker#94]
I have seen time picker demo on web browser and found time picker's time is not edible through keyborad. It just can be changed through arrows provided. 

Will it be editable through Native keyboard inside phonegap/cordova app?

**Comment by MayankLogiciel** [comment]
@rajeshwarpatlolla  thanks for amazing plugin.... It will be nice if we get editable time input in time picker. 
Please comment on this.

**Comment by rajeshwarpatlolla** [comment]
No, you won't be able to edit the time from the keyboard.

**Comment by philonor** [comment]
@rajeshwarpatlolla Are there certain reasons for not supporting manual editing? I'd like to know as I need to implement it anyway and would like to provide a PR.

**Comment by rajeshwarpatlolla** [comment]
It will open up keyboard. So it will be like, page, and on top of it popup and on top of it keyboard. Too many layers right?
