### ISSUE TITLE
set meridian from configuration object

### ISSUE THREAD

**Issue by ishamrozeraza** [rajeshwarpatlolla/ionic-timepicker#96]
can we set  meridian from configuration object such that ?

```
var timePickerObject = {
            callback: function (val) {   
            },
            meridian: "AM" // something like that...
            inputTime: 50400,   //Optional
            format: 12,         //Optional
            step: 10,           //Optional
            setLabel: 'Set Shift Time'    //Optional
        };
```

Basically in my case , i need to show a popup but i need to hide the AM PM option , keeping the format as 12 , because i ask user to filter as AM PM before showing the popup , so for this reason, i need to hide AM PM options, which i can through css . but I need to send time , as "AM" / "PM" what ever user has initially queried for. so i was wondering if i can have an option to set meridian the way i stated above.

**Comment by rajeshwarpatlolla** [comment]
The meridian is calculated based on the format field. So we don't actually need meridian field.
